num_layers: 64
num_kv_heads: 8
head_size: 128
dtype: bfloat16
use_mla: false
tp_size: 1
dp_size: 1
tokens_per_block: 16

cpu_cache_gb: 8
ssd_cache_gb: 16
ssd_cache_dir: ./ssd_cache1/;./ssd_cache2/
enable_gds: false
