cuda_graph_config:
  enable_padding: true
  batch_sizes:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
enable_chunked_prefill: true
kv_cache_config:
  enable_partial_reuse: false
  free_gpu_memory_fraction: 0.75
kv_connector_config:
  connector_module: "flexkv.integration.tensorrt_llm.trtllm_adapter"
  connector_scheduler_class: "FlexKVSchedulerConnector"
  connector_worker_class: "FlexKVWorkerConnector"
# disable_overlap_scheduler: true
speculative_config:
    decoding_type: MTP
    num_nextn_predict_layers: 3